#!/usr/bin/env python3
"""Scan assets/diagrams/<provider>/<category>/<name>.png and generate the
reference-notation catalog the Systems kit resolves.

Reference notation:
  provider:name             e.g. "aws:lambda"  (first category wins on collision)
  provider:category/name    e.g. "aws:network/internet-gateway"  (always unique)

Emits:
  src/kits/diagram_icons.rs   compiled-in `ICONS` table + `path()` lookup
  assets/diagrams-manifest.json   reviewable JSON of the same data

DSL grammar is unchanged — a node kind is still just a string. This is pure data.
"""
import os, json, collections

ROOT = "assets/diagrams"
entries = {}                                    # key -> "diagrams/..."
providers = collections.Counter()
bare_seen = {}

for provider in sorted(os.listdir(ROOT)):
    pdir = os.path.join(ROOT, provider)
    if not os.path.isdir(pdir):
        continue
    for dirpath, _, files in os.walk(pdir):
        for f in sorted(files):
            if not f.endswith(".png"):
                continue
            name = f[:-4]
            rel = os.path.relpath(os.path.join(dirpath, f), "assets").replace(os.sep, "/")
            # category = first path segment under the provider (or "" if provider-root)
            inner = os.path.relpath(dirpath, pdir).replace(os.sep, "/")
            cat = "" if inner == "." else inner.split("/")[0]
            # always-unique qualified key
            qkey = f"{provider}:{cat}/{name}" if cat else f"{provider}:{name}"
            entries[qkey] = rel
            # bare key — first category encountered wins (deterministic: sorted walk)
            bkey = f"{provider}:{name}"
            if bkey not in bare_seen:
                bare_seen[bkey] = rel
            providers[provider] += 1

for k, v in bare_seen.items():
    entries.setdefault(k, v)

rows = sorted(entries.items())

# --- emit the compiled-in Rust manifest ---
rs = ["// GENERATED by scripts/gen-diagram-manifest.py from assets/diagrams/. DO NOT EDIT.",
      "// Reference-notation catalog: `provider:name` (or `provider:category/name`)",
      "// -> asset-relative icon path. Disk-loaded at render time (no binary bloat).",
      "",
      "/// Sorted `(kind, asset_path)` pairs; look up with [`path`].",
      "pub static ICONS: &[(&str, &str)] = &["]
for k, v in rows:
    rs.append(f'    ("{k}", "{v}"),')
rs += ["];",
       "",
       "/// Resolve a `provider:name` kind (e.g. `aws:lambda`) to its icon path.",
       "pub fn path(kind: &str) -> Option<&'static str> {",
       "    ICONS.binary_search_by(|(k, _)| (*k).cmp(kind)).ok().map(|i| ICONS[i].1)",
       "}",
       ""]
open("src/kits/diagram_icons.rs", "w").write("\n".join(rs))

# --- emit reviewable JSON ---
json.dump({"root": "diagrams", "entries": dict(rows)},
          open("assets/diagrams-manifest.json", "w"), indent=0)

# --- emit the book reference chapter: reference notation + aliases + per-provider ---
# Friendly aliases mirror `canonical_provider_kind` in src/kits/systems.rs.
ALIASES = [
    ("aws:apigateway", "aws:api-gateway"),
    ("aws:route53", "aws:route-53"),
    ("aws:elb", "aws:elastic-load-balancing"),
    ("aws:load-balancer", "aws:elastic-load-balancing"),
    ("aws:sqs", "aws:simple-queue-service-sqs"),
    ("aws:s3", "aws:simple-storage-service-s3-bucket"),
    ("aws:ecs", "aws:elastic-container-service"),
    ("aws:eks", "aws:elastic-kubernetes-service"),
]
bare_by_provider = {}
for k in sorted(entries):
    if "/" in k:
        continue
    prov, name = k.split(":", 1)
    bare_by_provider.setdefault(prov, []).append(name)

md = []
md.append("# Diagrams — icon reference & aliases\n")
md.append("Every diagram node takes a **provider:name** string that selects *artwork "
          "only* — it never implies routing, balancing, queueing, or persistence. "
          f"The catalogue covers **{len(providers)} providers / {sum(providers.values())} "
          "components**, generated from `assets/diagrams/` by "
          "`scripts/gen-diagram-manifest.py` (Mingrammer/Diagrams icon set, disk-loaded at "
          "render — no binary bloat).\n")
md.append("## Reference notation\n")
md.append("- `provider:name` — e.g. `node(x, arch, \"aws:lambda\", \"fn\")`, "
          "`\"gcp:bigquery\"`, `\"onprem:redis\"`, `\"k8s:pod\"`. First matching category "
          "wins for the bare name.\n"
          "- `provider:category/name` — disambiguates when the same name lives in two "
          "categories of one provider, e.g. `\"aws:network/internet-gateway\"` vs "
          "`\"aws:general/internet-gateway\"`.\n"
          "- Native archetypes need **no** provider: `client`, `service`, `gateway`, "
          "`database`, `cache`, `queue`, `storage`, `external` (no cloud assets).\n")
md.append("## Friendly aliases\n")
md.append("Short, human names resolve to the exact catalogue key — same artwork either way:\n")
md.append("| Alias | Resolves to |\n|---|---|")
for a, t in ALIASES:
    md.append(f"| `{a}` | `{t}` |")
md.append("\nEverything else passes through unchanged: `aws:lambda`, `gcp:*`, `azure:*`, "
          "`onprem:*`, `k8s:*`, `ibm:*`, `oci:*`, … all resolve directly.\n")
md.append("## Colouring paths by relationship\n")
md.append("A `connect(id, …)` exposes two colourable parts — the cold dashed line `id` and "
          "the hot overlay `id.hot`. Group connections by relationship and colour each "
          "group (`color`/`hue`/`glow`/`dashed`/`stroke`) so a dense diagram reads at a "
          "glance:\n")
md.append("```manic\ncolor(reqPath, cyan);   color(reqPath.hot, cyan);    // REQUEST\n"
          "color(logPath, gold);   color(logPath.hot, gold);    // ANALYTICS\n"
          "hue(scrape, 328);       hue(scrape.hot, 328);         // TELEMETRY (pink)\n```\n")
md.append("## Providers & components\n")
md.append("Any listed name works as `provider:name`. Full machine-readable catalogue: "
          "`assets/diagrams-manifest.json`.\n")
for prov in sorted(bare_by_provider):
    names = bare_by_provider[prov]
    sample = ", ".join(f"`{prov}:{n}`" for n in names[:14])
    more = f" … (+{len(names) - 14} more)" if len(names) > 14 else ""
    md.append(f"### `{prov}` — {len(names)} components\n{sample}{more}\n")
open("book/src/systems-icons.md", "w").write("\n".join(md) + "\n")

print(f"providers : {len(providers)}")
print(f"keys      : {len(rows)}  (bare + qualified)")
print(f"per provider: {dict(providers)}")
print("wrote src/kits/diagram_icons.rs + assets/diagrams-manifest.json")
